### ISSUE TITLE
Tried To Install It 

### ISSUE THREAD

**Issue by bioinfonerd** [clemenshug/enrichr.db#1]
> if (!requireNamespace("remotes", quietly = TRUE))
+   install.packages("remotes")
> remotes::install_github("clemenshug/enrichr.db")
Downloading GitHub repo clemenshug/enrichr.db@master
√  checking for file 'C:\Users\Nathan\AppData\Local\Temp\RtmpiO1CaQ\remotes5f6c4077c70\clemenshug-enrichr.db-8cb1a3d/DESCRIPTION' (464ms)
-  preparing 'enrichr.db':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'enrichr.db_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/Nathan/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'enrichr.db' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: file 'enrichr_terms.rda' has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package 'enrichr.db'
* removing 'C:/Users/Nathan/Documents/R/win-library/3.6/enrichr.db'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Nathan/AppData/Local/Temp/RtmpiO1CaQ/file5f6c8f11b/enrichr.db_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by clemenshug** [comment]
Thanks Nathan! It looks like Git LFS was required to download the repo correctly. I switched to distributing the package as binary release instead, that should hopefully work easier.
